### ISSUE TITLE
Example Project 

### ISSUE THREAD

**Issue by FlameBearer** [alvinfrancis/opentracing-clj#3]
Is there a project you know of that uses this dependencies that I can use as example? New to clojure trying to get the tracing to work off of the readme examples but struggle see anything in the logs.

**Comment by alvinfrancis** [comment]
Your mention of expecting to see things (traces?) in logs makes me think that maybe you have this confused for something else.  Tracing here refers to distributed tracing, which is a means to observe applications interacting with each other, primarily in a microservices architecture

Perhaps you're looking for https://github.com/clojure/tools.trace instead?  That's a trace tool that's more meant to be used with a logging system.

I hope I'm not misunderstanding your question.  If I am misunderstanding your intent, and you are looking to get a grasp on using this opentracing library, then I can suggest going through the tests to get an idea of the behaviour of the library.  And I suggest going through the documentation in https://opentracing.io/ to make sure you're looking for the right tool.

Hope that helps!

**Comment by FlameBearer** [comment]
I am looking for a distributed tracing library, I just may be using the wrong terms.  Took another look at the documentation for open tracing and I guess a better question is where are all the spans/span context for a single trace exported to? In my past experience with java you would see the tran_id and span_id in the logs.

Thanks for all the suggesting.  I will go through the test and see if that helps be get a better idea of the behaviour of the library.

**Comment by alvinfrancis** [comment]
Ah my bad then.  Sorry for misunderstanding you.  To answer your question on where the spans are exported to, that really depends on the tracer implementation you'll be using as OpenTracing is just the API.  For a minimal example of using this library in concert with an actual OpenTracing implementation, I've made the following gist:

https://gist.github.com/alvinfrancis/4ad9a96b0d24d7f563315f08a5d9c97a

Just copy the `deps.edn` and `example.clj` files to their own folder and follow the README.  Hopefully that helps clears thing up somewhat.

I might also look into setting up a more thorough example project here in the future.  For now I hope the small sample up there can get you started.

**Comment by FlameBearer** [comment]
Thank you! That helped a lot 👍
