### ISSUE TITLE
response instead of request?

### ISSUE THREAD

**Issue by wontheone1** [alvinfrancis/opentracing-clj#6]
I am new to opentracing so I might be reporting false issue, let me know if I make sense at all.

From the readme
https://github.com/alvinfrancis/opentracing-clj#propagation

```
(let [response (http-ring-response) ; assuming this is an HTTP call returning a ring spec response
      ctx      (propagation/extract (:headers request) :http)]
  (tracing/with-span [s {:name     "child-of-propagation"
                         :child-of ctx}]
    ... ; this span will be recorded as a child of the span context propagated through the HTTP call
    ))
```
There is no binding of `request` in the example code so I wonder if you meant `response` not `request`?

**Comment by alvinfrancis** [comment]
Good catch!  Been a while but looking at that piece of code again, and it's definitely off.  Doesn't make sense though that I would have meant `response` especially considering that one wouldn't normally set the caller the child of the callee.  Correction would be that the response binding should have been a binding to some inbound request.  I don't know what I was thinking.

Still thanks for catching that.  I'll fix it in the README in a bit.
